fix!: revamp everything
catppuccin/aliucord pull request #6
Opened 2024-06-30 14:00 UTC by myumichi

* remade themes from scratch
* updated previews
* updated docs
* added fonts used with theme

with these changes i also plan to add multiple different accent colors, later down the line.

2024-06-30 14:29 UTC, sgoudham requested changes
A fair few comments on this sorry! 
Just trying to make sure it matches with the existing theme / links are updated.

Also I have some comments surrounding the inclusion of font files, would appreciate if you could help me understand why they were included, thanks!

2024-06-30 14:29 UTC, sgoudham commented on README.md
> +  <img src="https://raw.githubusercontent.com/myumichi/aliucord-fork/main/assets/preview.webp"/>
```suggestion
  <img src="./assets/preview.webp"/>
```

2024-06-30 14:29 UTC, sgoudham commented on README.md
> +<img src="https://raw.githubusercontent.com/myumichi/aliucord-fork/main/assets/latte-preview.webp"/>
```suggestion
<img src="./assets/latte.webp"/>
```

2024-06-30 14:29 UTC, sgoudham commented on README.md
> +<img src="https://raw.githubusercontent.com/myumichi/aliucord-fork/main/assets/frappe-preview.webp"/>
```suggestion
<img src="./assets/frappe.webp"/>
```

2024-06-30 14:29 UTC, sgoudham commented on README.md
> +<img src="https://raw.githubusercontent.com/myumichi/aliucord-fork/main/assets/macchiato-preview.webp"/>
```suggestion
<img src="./assets/macchiato.webp"/>
```

2024-06-30 14:29 UTC, sgoudham commented on README.md
> +<img src="https://raw.githubusercontent.com/myumichi/aliucord-fork/main/assets/mocha-preview.webp"/>
```suggestion
<img src="./assets/mocha.webp"/>
```

2024-06-30 14:29 UTC, sgoudham commented on assets/fonts/Manrope-Bold.ttf
Is there a reason why we need to specify these fonts as part of the theme? As a colourscheme, we should focus purely on the highlighting and avoid shipping stylistic changes like fonts.

Let me know if this is included for another reason though.

2024-06-30 14:29 UTC, sgoudham commented on assets/frappe-preview.webp
Should be renamed to `frappe.webp`

2024-06-30 14:29 UTC, sgoudham commented on assets/latte-preview.webp
Should be renamed to `latte.webp`

2024-06-30 14:29 UTC, sgoudham commented on assets/macchiato-preview.webp
Should be renamed to `macchiato.webp`

2024-06-30 14:29 UTC, sgoudham commented on assets/mocha-preview.webp
Should be renamed to `mocha.webp`

2024-06-30 14:29 UTC, sgoudham commented on src/frappe.json
> +        "updater": "https:\/\/raw.githubusercontent.com\/myumichi\/aliucord\/main\/src\/frappe.json"
```suggestion
        "updater": "https:\/\/raw.githubusercontent.com\/catppuccin\/aliucord\/main\/src\/frappe.json"
```

2024-06-30 14:29 UTC, sgoudham commented on src/frappe.json
> +        "version": "1.0.0",
Probably makes more sense to bump this to the next major version?
```suggestion
        "version": "2.0.0",
```

2024-06-30 14:29 UTC, sgoudham commented on src/frappe.json
> +    },
See comment above for the font files, do we need to ship these?

2024-06-30 14:29 UTC, sgoudham commented on src/latte.json
> +        "updater": "https:\/\/raw.githubusercontent.com\/myumichi\/aliucord\/main\/src\/latte.json"
```suggestion
        "updater": "https:\/\/raw.githubusercontent.com\/catppuccin\/aliucord\/main\/src\/latte.json"
```

2024-06-30 14:29 UTC, sgoudham commented on src/macchiato.json
> +        "updater": "https:\/\/raw.githubusercontent.com\/myumichi\/aliucord\/main\/src\/macchiato.json"
```suggestion
        "updater": "https:\/\/raw.githubusercontent.com\/catppuccin\/aliucord\/main\/src\/macchiato.json"
```

2024-06-30 14:29 UTC, sgoudham commented on src/mocha.json
> +        "updater": "https:\/\/raw.githubusercontent.com\/myumichi\/aliucord\/main\/src\/mocha.json"
```suggestion
        "updater": "https:\/\/raw.githubusercontent.com\/catppuccin\/aliucord\/main\/src\/mocha.json"
```

2024-06-30 14:29 UTC, sgoudham commented on src/latte.json
> +        "version": "1.0.0",
See prior comment about the version

2024-06-30 14:29 UTC, sgoudham commented on src/latte.json
> +    },
See prior comment about the fonts

2024-06-30 14:29 UTC, sgoudham commented on src/macchiato.json
> +    },
See prior comment about the fonts

2024-06-30 14:29 UTC, sgoudham commented on src/mocha.json
> +    },
See prior comment about the fonts

2024-06-30 14:29 UTC, sgoudham commented on src/mocha.json
> +        "version": "1.0.0",
See prior comment about version

2024-06-30 14:29 UTC, sgoudham commented on src/macchiato.json
> +        "version": "1.0.0",
See prior comment about version

2024-06-30 14:29 UTC, sgoudham commented on src/frappe.json
> +        "name": "catppuccin frappé",
Feels like we should keep the name the same as the existing themes
```suggestion
        "name": "Catppuccin Frappe",
```

2024-06-30 14:29 UTC, sgoudham commented on src/latte.json
> +        "name": "catppuccin latte",
```suggestion
        "name": "Catppuccin Latte",
```

2024-06-30 14:29 UTC, sgoudham commented on src/macchiato.json
> +        "name": "catppuccin macchiato",
```suggestion
        "name": "Catppuccin Macchiato",
```

2024-06-30 14:29 UTC, sgoudham commented on src/mocha.json
> +        "name": "catppuccin mocha",
```suggestion
        "name": "Catppuccin Mocha",
```

2024-06-30 14:56 UTC, myumichi commented
i can remove the font directory and update the .jsons to remove them if wanted, i figured it _could_ have been optional as they're fairly easy to remove once you open the theme in aliucord

everything else will be updated shortly

2024-06-30 15:00 UTC, myumichi commented
the previews reflecting the theme **without the fonts** take a while updating as everything was done on my phone, sorry in advance

2024-06-30 17:06 UTC, sgoudham commented on README.md
> +<img src=assets/mocha.webp"/>
```suggestion
<img src="assets/mocha.webp"/>
```

2024-07-01 11:07 UTC, sgoudham commented on README.md
> +- A: Yes, new accents will be added each week. (hopefully)
This can be tracked in an issue instead of on the README.

```suggestion
```

2024-07-01 11:08 UTC, sgoudham commented on README.md
> +- A: The introduction of Material You has affected devices on Android 12+, and some areas may not render correctly. If you are on a Custom ROM, please look at [this fix.](https://rentry.co/ThemerFixe
```suggestion
  A: The introduction of Material You has affected devices on Android 12+, and some areas may not render correctly. If you are on a Custom ROM, please look at [this fix.](https://rentry.co/ThemerFixer)
```

2024-07-01 11:08 UTC, sgoudham commented on README.md
> +  A: The introduction of Material You has affected devices on Android 12+, and some areas may not render correctly. If you are on a Custom ROM, please look at [this fix.](https://rentry.co/ThemerFixe
```suggestion
- Q: **_Why can't I see X thing themed?_**
   
   A: The introduction of Material You has affected devices on Android 12+, and some areas may not render correctly. If you are on a Custom ROM, please look at [this fix.](https://rentry.co/ThemerFixer)
```

2024-07-01 11:10 UTC, sgoudham commented on README.md
> +  - SquareAvatars
```suggestion
- Q: **_Which plugins are used in the screenshots?_**

  A: The plugins included are:
  	- BetterChatbox
  	- BetterStatusIndicators
  	- BetterChannelIcons
  	- BetterDashless
  	- NoBurnIn
  	- LayoutController
  	- SquareAvatars
```

2024-07-01 11:13 UTC, sgoudham approved these changes
Looks good now, thanks!
The preview images can be updated in a later PR if it'll take some time for you to do it, no rush!

2024-07-01 19:13 UTC, merged